version: '3'

services:
  image_uploader_api:
    build: "./image-uploader-api"
    ports:
      - 3000:3000
    links:
      - redis
    depends_on:
      - rabbitmq

  mail_service:
    build: "./mail-service"
    depends_on:
      - rabbitmq

  redis:
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672